clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: flt_analytics_dev
      host: 192.168.10.202
      port: 30123
      user: admin
      password: admin123
      connect_timeout: 10
      secure: False

    prod:
      type: clickhouse
      schema: flt_analytics
      host: clickhouse-external.clickhouse-db.svc.cluster.local
      port: 8123
      user: dbt_user
      password: "{{ env_var('DBT_PASSWORD') }}"
